# series 1d array


In [3]:
import pandas as pd
a=pd.Series([10,30,50])
print(a)

0    10
1    30
2    50
dtype: int64


In [20]:
import pandas as pd
a=pd.Series([10,30,50],index=[4,3,6])
print(a)

4    10
3    30
6    50
dtype: int64


# 2D array DataFrame

In [6]:
import pandas as pd
a=pd.DataFrame({"abc":[123],"def":[456]})
print(a)

   abc  def
0  123  456


In [14]:
import numpy as np
a=np.array([1,2,3])
print(a)
np.zeros(3)
np.ones(5)


[1 2 3]


array([1., 1., 1., 1., 1.])

In [16]:
print(a)
np.zeros(3)

[1 2 3]


array([0., 0., 0.])

In [17]:
np.arange(4)

array([0, 1, 2, 3])

In [18]:
np.arange(3,10,4)

array([3, 7])

In [22]:
arr=np.array([2,1,5,3,7,4,6,8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
import numpy as np
a=np.arange(15).reshape(3,5)
a




array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
a.shape


(3, 5)

In [22]:
a.ndim

2

In [23]:
a.dtype.name

'int32'

In [24]:
type(a)

numpy.ndarray

In [28]:
a.itemsize


4

In [27]:
a.size

15

In [1]:
dic={"abc":1,"def":2}
import pandas as pd
a=pd.Series(dic)
print(a)

abc    1
def    2
dtype: int64


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [5]:
import numpy as np
a=np.array(4)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# accessing 1d elements

In [7]:
print(b[2]+b[3])

7


In [9]:
print(b[2]*b[3])

12


In [11]:
print(b[2])

3


# accessing 2d elements

In [13]:
import numpy as np
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2[0,1])
print(arr2[1,2])


2
6


# accessing 3d elements

In [14]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])
print(arr[1,0,0])

6
7


In [22]:
import numpy as np
b=np.array([1,2,3,4,5,6,7,8])
print(b[1:5])
print(b[2:4])
print(b[4:])
print(b[:4])
print(b[-3:-1])
print(b[1:5:2])
print(b[0:7:3])

[2 3 4 5]
[3 4]
[5 6 7 8]
[1 2 3 4]
[6 7]
[2 4]
[1 4 7]
